spring:
  datasource:
    url: jdbc:h2:file:./database/jdvsdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none

jdvs:
  config-path: ./jdvs.yml
  base-dir: ./javadoc-storage
  cron: 0 0/15 * * * ?
  run-on-start: false
